services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - ./dynamodb_local:/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    restart: always
    ports:
      - '8001:8001'
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=us-east-1
    depends_on:
      - dynamodb
