name: Publish

on:
  push:
    tags:
      - v*.*.*
      - 'release/*/[0-9]*.[0-9]*.[0-9]*'

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm exec nx affected -t lint test build

      - name: Print Environment Info
        run: pnpx nx report
        shell: bash

      - name: Publish packages
        run: pnpx nx release publish --access=public
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
